### ISSUE TITLE
memory leak in file "at.c"

### ISSUE THREAD

**Issue by EduardShaid** [OpenPhoenux/gta04-replicant-device#1]
In "at.c" file to invoke(at_request_send(...)) for the function asprintf (& data, "% s% s% s", separator, request-> string, separator); no function free(data), to clear the allocated memory. There will be a memory leak. See whether this is so.

**Comment by slyon** [comment]
Github is just a mirror for this project. Please report issues at the official project forge:
http://projects.goldelico.com/p/gta04-replicant

I've copied this issue over for you: http://projects.goldelico.com/p/gta04-replicant/issues/633/

**Comment by slyon** [comment]
Fixed.
http://git.goldelico.com/?p=gta04-replicant-device.git;a=commit;h=6b0fb78cda2669dfc0b63c361f60290a646e8f89
